[package]
name = "dpll-sat"
version = "0.1.0"
authors = ["snsinfu <snsinfu@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
